[build]
builder = "NIXPACKS"

[build.nixpacksPlan]
providers = ["java"]

[build.nixpacksPhases.setup]
nixPkgs = ["openjdk21", "gradle_8"]

[build.nixpacksPhases.install]
cmds = ["echo 'Java version:' && java -version"]

[build.nixpacksPhases.build]
cmds = ["chmod +x ./gradlew", "./gradlew clean bootJar --no-daemon -x test"]

[deploy]
startCommand = "java -Dserver.port=$PORT $JAVA_OPTS -jar build/libs/asistencia-backend.jar"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
